development:
  adapter: postgresql
  encoding: unicode
  database: countries_dev
  pool: 5
  host: localhost
  username: dev
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: countries_test
  pool: 5
  host: localhost
  username: dev
  password:
